### ISSUE TITLE
[Post Quarkus Migration] Add /auth redirection?

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#139]
## Context
The original behavior of Wildly was having an redirect from / to /auth. After the migration you just get a "Resource not found".

## Alternatives
Keep without.

**Comment by megian** [comment]
Potentially we could run the application itself on `/`, but do a rewrite on `/auth`in the ingress if required.

**Comment by simu** [comment]
> Potentially we could run the application itself on `/`, but do a rewrite on `/auth`in the ingress if required.

Could work on clusters with ingress controllers which support path type `Exact` for ingress paths. However, for example the OpenShift 4 ingress-to-route controller explicitly doesn't support that path type, so this won't work reliably across different Kubernetes distributions.

**Comment by megian** [comment]
In Keycloak v20 the [admin url](https://www.keycloak.org/2022/11/keycloak-2000-released) can be different to the fronted url and might fix this.

**Comment by megian** [comment]
> In Keycloak v20 the [admin url](https://www.keycloak.org/2022/11/keycloak-2000-released) can be different to the fronted url and might fix this.

It isn't. Set the Keycloak itself to `/` and redirect `/auth` to `/`at an ingress level could be an other option.

**Comment by megian** [comment]
Set the Keycloak itself to `/` and rewrite `/auth` to `/`at an ingress level does work in a first test.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: keycloakx-auth-rewrite
  namespace: syn-keycloak-test
spec:
  ingressClassName: nginx
  rules:
  - host: id.test.example.com
    http:
      paths:
      - backend:
          service:
            name: keycloakx-http
            port:
              name: https
        path: /auth(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - id.test.example.com
    secretName: ingress-tls
```
