### ISSUE TITLE
Component v9.0.0 external database hostname is not taken

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#151]
The component must take the external hostname into helm_values.
```
parameters:
  keycloak:
    database:
      provider: external
      external:
        host: postgres.example.com
```
Currently the database hostname is hardcoded.
```        
helm_values:
  database:
    hostname: postgres.example.com
```

## Actual Behavior
Database hostname is hardcoded to keycloak-postgresql rather than danymic.

## Expected Behavior
The external defined hostname is taken if the database provider is external.
