### ISSUE TITLE
Hardening to PSA restricted

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#181]
## Context
With the more growing ability to harden deployments with [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) and [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/), Keycloak as a security component should use all the capabilities to prevent security flaws.

```
parameters:
  keycloak:
    namespaceLabels:
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/enforce: restricted
      pod-security.kubernetes.io/warn: restricted
```
Keycloak and Bitnami Postgres currently do work in a fully restricted mode. However k8up doing to Bitnami Postgres backup, is currently not able to set the container securityContext. See k8up-io#584.

Currently the baseline mode does work:
```
parameters:
  keycloak:
    namespaceLabels:
      pod-security.kubernetes.io/audit: baseline
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/warn: restricted
```

## Alternatives
* None
