### ISSUE TITLE
The networkpolicy provided by the Helm chart (if enabled) does not allow the ingress controller access to Keycloak

### ISSUE THREAD

**Issue by simu** [projectsyn/component-keycloak#19]
When deploying the component with network policy enabled, the `NetworkPolicy` object which is created looks as follows:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 12.0.4
    argocd.argoproj.io/instance: keycloak
    helm.sh/chart: keycloak-10.3.1
  name: keycloak
  namespace: keycloak
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: keycloak
          app.kubernetes.io/name: keycloak
    ports:
    - port: 80
      protocol: TCP
    - port: 8443
      protocol: TCP
    - port: 9990
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  policyTypes:
  - Ingress

```

Note that this policy will prohibit any ingress traffic to the Keycloak pods, except traffic originating from another keycloak pod.

## Steps to Reproduce the Problem

  1. Install keycloak component with `helmValues.networkPolicy.enabled=true` and `ingress.enabled=true`

## Actual Behavior

* Observe that the Keycloak interface is not reachable over the ingress with a 504
* Observe that the Keycloak interface is reachable over the ingress when the NetworkPolicy object is removed

## Expected Behavior

* Keycloak is reachable when NetworkPolicy is enabled

**Comment by simu** [comment]
Figure out what we need to set in the Helm chart in `networkPolicy.extraFrom` to allow traffic from the ingress controller.

**Comment by megian** [comment]
This config did work:
```
parameters:
  keycloak:
    helm_values:
      networkPolicy:
        enabled: true
        extraFrom:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              name: syn-ingress-nginx
```
Be aware of, that this is only working with TLS (8443) as the port 80 is valid for the service itself, but since Keycloak listen on port 8080 that didn't work for me.

**Comment by ccremer** [comment]
On a related note: I created upstream PR https://github.com/codecentric/helm-charts/pull/432 to fix the container port in the netpol.
Doesn't fix the issue when connecting from ingress controller though.

**Comment by ccremer** [comment]
Also, we might get away from the port 80 restriction by setting `service.httpPort=8080` (https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml#L238) so it'll be the same as the container port, then even without the fix upstream, it should work.

Just in case the upstream PR takes very long to merge...

**Comment by tobru** [comment]
Little helper: https://editor.cilium.io/

**Comment by ccremer** [comment]
> This config did work:
> 
> ```
> parameters:
>   keycloak:
>     helm_values:
>       networkPolicy:
>         enabled: true
>         extraFrom:
>         - podSelector:
>             matchLabels:
>               app.kubernetes.io/name: ingress-nginx
>         - namespaceSelector:
>             matchLabels:
>               name: syn-ingress-nginx
> ```
> 

Be aware that you allowed ALL pods from syn-ingress-nginx to connect. If you only want the ingress pods to be able to connect, you should combine the namespace and pod selector like this:
```
parameters:
  keycloak:
    helm_values:
      networkPolicy:
        enabled: true
        extraFrom:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
          namespaceSelector:
            matchLabels:
              name: syn-ingress-nginx
```
(notice the selectors are in the same array)
see also https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors
