### ISSUE TITLE
Feature: Add k8up support

### ISSUE THREAD

**Issue by megian** [projectsyn/component-keycloak#22]
## Context
The keycloak database must be backup'ed. So adding support for k8up (disabled by default) gives an easy possibility to do this backup.

Add the backup annotation to the postgres db:
```
template:
  metadata:
    labels:
      app: mariadb
    annotations:
      k8up.syn.tools/backupcommand: sh -c 'PGDATABASE="$POSTGRES_DB" PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" pg_dump'
```

Required additional objects:
```
apiVersion: v1
data:
  password: XXX
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/instance: syn-keycloak
    name: k8up-restic-password
  name: k8up-restic-password
  namespace: syn-keycloak
type: Opaque

apiVersion: v1
data:
  password: XXX
  username: XXX
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/instance: cluster-backup
    name: keycloak-database-k8up-s3-credentials
  name: keycloak-database-k8up-s3-credentials
  namespace: syn-keycloak

apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  labels:
    argocd.argoproj.io/instance: syn-keycloak
  name: database-backup
  namespace: syn-keycloak
spec:
  backend:
    repoPasswordSecretRef:
      key: password
      name: k8up-restic-password
    s3:
      accessKeyIDSecretRef:
        key: username
        name: keycloak-database-k8up-s3-credentials
      bucket: k8up-<cluster>-syn-keycloak
      endpoint: https://s3.eu-central-1.amazonaws.com
      secretAccessKeySecretRef:
        key: password
        name: keycloak-database-k8up-s3-credentials
  backup:
    keepJobs: 5
    promURL: http://platform-prometheus-pushgateway.syn-synsights.svc:9091
    schedule: 30 * * * *
  check:
    promURL: http://platform-prometheus-pushgateway.syn-synsights.svc:9091
    schedule: 30 3 * * *
  prune:
    retention:
      keepDaily: 30
      keepLast: 20
    schedule: 10 */4 * * *
```
