### ISSUE TITLE
Automate Keycloak Updates

### ISSUE THREAD

**Issue by chloesoe** [projectsyn/component-keycloak#36]
## Context

To update to the newest version of Keycloak, we have to follow ~10 manual steps, including find out when a new version was released (https://quay.io/repository/keycloak/keycloak?tab=tags) and changing it on with commodore. 

Related to [SYN-352 Automated Component Dependency Updates](https://ticket.vshn.net/browse/SYN-352)
Current update procedure documented in [internal wiki](https://wiki.vshn.net/x/aYP-Cw#VSHNIDP-UpdateSteps)
Appeared during [VT-1556](https://ticket.vshn.net/browse/VT-1556)

## Alternatives
At the moment an update is done with helm_values, e.g.
```
  example_keycloak_prod:
    namespace: example-keycloak-prod
    fqdn: id.example.net
...
    helm_values:
      image:
        tag: 13.0.0
```
This is somehow bypassing component-keycloak and changing directly a value from the used helm chart. 

## As Operator of Keycloak on K8s...
* I want to get informed if a new release is available
* I want that a merge/pull request is created for my configured Keycloak statefulsets to update to that newest version
* I want that after merging the MR/PR that the new version is rolled out automatically.
