### ISSUE TITLE
Support custom theme

### ISSUE THREAD

**Issue by chloesoe** [projectsyn/component-keycloak#40]
## Context
In order to provide a custom theme [according to the codecentric documentation](https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/README.md#providing-a-custom-theme) we have to add extraInitContainers, extraVolumeMounts, and extraVolumes. 
In the component-keycloak that should be supported easily. At the moment we to copy the whole extraVolumes String ([see component-keycloak/defaults.yml](https://github.com/projectsyn/component-keycloak/blob/532880ab59f6966d0ebe1253d9ee13eb5a83f6d5/class/defaults.yml#L161-L179)) to our cluster definition file to add an additional volume.

For https://github.com/vshn/keycloak-theme/ we have to add the values below, but we also have to copy everything from [defaults.yml](https://github.com/projectsyn/component-keycloak/blob/master/class/defaults.yml#L161-L179), which leads to duplication. 
```yaml
      extraVolumes: |
        - name: db-certs
          secret:
            secretName: keycloak-postgresql-tls
            defaultMode: 0400
            items:
              - key: tls.crt
                path: tls.crt
        - name: keycloak-tls
          secret:
            secretName: keycloak-tls
            defaultMode: 420
        - name: theme
          emptyDir: {}
      extraVolumeMounts: |
        - name: db-certs
          readOnly: true
          mountPath: /opt/jboss/certs
        - name: keycloak-tls
          readOnly: true
          mountPath: /etc/x509/https
        - name: theme
          readOnly: true
          mountPath: /opt/jboss/keycloak/themes/vshn
      extraInitContainers: |
        - name: theme-provider
          image: quay.io/vshn/keycloak-theme:v1.0.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - |
              echo "Copying theme..."
              cp -R /theme/* /vshn-theme
          volumeMounts:
            - name: theme
              mountPath: /vshn-theme
```

## Acceptance criteria

* We only should only need to define the image name and mount points as parameters.
* Add a small how-to page describing how to develop a custom theme.

## Alternatives
Copy paste all extraVolume definitions from component-keycloak works but.
