### ISSUE TITLE
Openshift: Ingress not working out of the box

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-keycloak#80]
## Steps to Reproduce the Problem

  1. Prepare TLS cert as documented in https://hub.syn.tools/keycloak/how-tos/keycloak-tls.html
  1. Deploy keycloak to OpenShift 4.8
  1. Access ingress

## Actual Behavior

># 502 Bad Gateway
>The server returned an invalid or incomplete response.

## Expected Behavior
The application is served

**Comment by ccremer** [comment]
Can you share the parameters you used for an installation on OCP 4?
Because APPUiO Cloud is using parameters that work for an ingress.
Did you also consider https://hub.syn.tools/keycloak/how-tos/openshift-4.html?

**Comment by mhutter** [comment]
>Can you share the parameters you used for an installation on OCP 4?

<details><summary>Sure</summary>
```yaml
  keycloak_test:
    namespace: keycloak-test
    ingress:
      servicePort: http
    fqdn: test.anmeldung.example.ch

    admin:
      username: '?{vaultkv:${cluster:tenant}/${cluster:name}/keycloak-test/admin-username}'
      password: '?{vaultkv:${cluster:tenant}/${cluster:name}/keycloak-test/admin-password}'

    database:
      tls:
        enabled: false

      provider: external

      external:
        host: maxscale-masteronly
        vendor: mariadb
        port: 3306

      database: keycloak_test
      username: keycloak_test

    extraInitContainers:
      theme-provider:
        image: image-registry.openshift-image-registry.svc:5000/tpl-build-integration/example-keycloak-theme:test
        imagePullPolicy: Always
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -Rv /themes/* /target/
        volumeMounts:
          - name: themes
            mountPath: /target
    extraVolumes:
      themes:
        emptyDir: {}

    helm_values:
      image:
        tag: 14.0.0
      podSecurityContext: null
      securityContext: null
      pgchecker:
        securityContext: null
      extraVolumeMounts: |
        - name: keycloak-tls
          readOnly: true
          mountPath: /etc/x509/https
        - name: themes
          mountPath: /opt/jboss/keycloak/themes/example
          subPath: example
        - name: themes
          mountPath: /opt/jboss/keycloak/themes/app1
          subPath: example
        # ... snip ...
```
</details>

>Did you also consider https://hub.syn.tools/keycloak/how-tos/openshift-4.html?

Yes we did.

The setup where we discovered those issues have been removed again, but we'll set up a development environment that we can use for investigations soon.

**Comment by ccremer** [comment]
I did spot the issue :see_no_evil: 
It's a classic YAML indentation problem. The `ingress.servicePort` should be beneath `helm_values`. This is wrong in the docs.
The config should be:
```yaml
  keycloak_test:
    ...
    helm_values:
      ingress:
        servicePort: http
```
Once you fixed this, can you please try again?
Meanwhile I'll open a PR
